export default region => ({
  results: [
    {
      jobtitle             : 'Software Engineer', 
      company              : 'Google', 
      formattedRelativeTime: '12 days ago', 
      snippet              : 'Full time engineer needed to work on expanding and maintaining Google Search. Five years experience is helpful, but not a must. Ability to collaborate with a large team in a highly competitive environment is required.', 
      latitude             : region.latitude, 
      longitude            : region.longitude, 
      jobkey               : '1',
      url                  : 'http://www.indeed.com/viewjob?jk=0db27d0c3cb9af17&qd=REwda0rWYViawD3-x4Y3w1RDVCoGfgb40m-71nYVPLwRdIPXjia8IlldvSzwyXqep0BNjXI9RCalenF748nLRD18R4J5iq5RSEylbuAi5jg',
    },
    {
      jobtitle             : 'Junior React Developer',
      company              : 'Nerdo Coffee', 
      formattedRelativeTime: '24 hours ago', 
      snippet              : 'New coffee delivery service is in need of a mobile app and website. We roast the organic, fair trade Argentine beans in our van as we drive around brewing lattes. You will be coding in the same van.', 
      latitude             : region.latitude, 
      longitude            : region.longitude, 
      jobkey               : '2',
      url                  : 'http://www.indeed.com/viewjob?jk=0db27d0c3cb9af17&qd=REwda0rWYViawD3-x4Y3w1RDVCoGfgb40m-71nYVPLwRdIPXjia8IlldvSzwyXqep0BNjXI9RCalenF748nLRD18R4J5iq5RSEylbuAi5jg',
    },
    {
      jobtitle             : 'Angular Master', 
      company              : 'Fishing Fanatics', 
      formattedRelativeTime: '22 days ago', 
      snippet              : 'Large fishing retail chain is looks for a master at Angular. Applicant needs to understand the ridiculous module system and templating annoyance. We have a quick hook if you cannot hang. ng not good.', 
      latitude             : region.latitude,
      longitude            : region.longitude,
      jobkey               : '3',
      url                  : 'http://www.indeed.com/viewjob?jk=0db27d0c3cb9af17&qd=REwda0rWYViawD3-x4Y3w1RDVCoGfgb40m-71nYVPLwRdIPXjia8IlldvSzwyXqep0BNjXI9RCalenF748nLRD18R4J5iq5RSEylbuAi5jg',
    },
    {
      jobtitle             : 'NodeJS Developer',
      company              : 'Pipe Dreams',
      formattedRelativeTime: '420 seconds ago', 
      snippet              : 'Recreational and medical marijuana dispensary is upgrading all backend servers to meet rapidly growing demands. We require someone with 3-5 years experience working with NodeJS. Cloud computing knowledge a plus.', 
      latitude             : region.latitude, 
      longitude            : region.longitude, 
      jobkey               : '4',
      url                  : 'http://www.indeed.com/viewjob?jk=0db27d0c3cb9af17&qd=REwda0rWYViawD3-x4Y3w1RDVCoGfgb40m-71nYVPLwRdIPXjia8IlldvSzwyXqep0BNjXI9RCalenF748nLRD18R4J5iq5RSEylbuAi5jg',
    },
    {
      jobtitle             : 'Remote Javascript', 
      company              : 'Snippets', 
      formattedRelativeTime: '7 days ago', 
      snippet              : 'Website development company looking for part time remote javascript developer. We need someone to add functionality and a dymanic feel to our websites, since we are more of a design centered team. Newbs need not apply',
      latitude             : region.latitude, 
      longitude            : region.longitude, 
      jobkey               : '5',
      url                  : 'http://www.indeed.com/viewjob?jk=0db27d0c3cb9af17&qd=REwda0rWYViawD3-x4Y3w1RDVCoGfgb40m-71nYVPLwRdIPXjia8IlldvSzwyXqep0BNjXI9RCalenF748nLRD18R4J5iq5RSEylbuAi5jg',
    },
  ],
})